// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilesPerGallon.Models;

namespace MilesPerGallon.Migrations
{
    [DbContext(typeof(MilesPerGallonContext))]
    [Migration("20191001150425_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MilesPerGallon.Models.DataPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarModel")
                        .IsRequired();

                    b.Property<DateTime>("FillUpDate");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("GallonsFilled");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<float>("MilesDriven");

                    b.HasKey("Id");

                    b.ToTable("DataPage");
                });
#pragma warning restore 612, 618
        }
    }
}
